spring.application.name=direct-debit-sandbox

server.port=8080


sandbox.callback-delay-preapproval=2000
sandbox.callback-delay-transaction=5000

# ── Swagger UI / SpringDoc ──────────────────────────────────────────────────
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.doc-expansion=none